# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert_guarantee.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql

class Ui_insert_guarantee(object):
    def insert(self):
        db = pymysql.connect("localhost","root","","bingung")
        cur = db.cursor()
        a = self.lineEdit_id.text()
        b = self.lineEdit_start.text()
        c = self.lineEdit_end.text()
        d = self.lineEdit_serial.text()
        e = self.lineEdit_guarantee.text()
        cur.execute("INSERT INTO guarantee VALUES ('"+a+"','"+b+"','"+c+"','"+d+"','"+e+"') ")
        db.commit()
    def setupUi(self, insert_guarantee):
        insert_guarantee.setObjectName("insert_guarantee")
        insert_guarantee.resize(800, 600)
        insert_guarantee.setStyleSheet("background-color: rgb(112, 112, 112);")
        self.centralwidget = QtWidgets.QWidget(insert_guarantee)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setGeometry(QtCore.QRect(331, 120, 181, 20))
        self.lineEdit_id.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 0, 801, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(171, 190, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.lineEdit_start = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_start.setGeometry(QtCore.QRect(331, 160, 181, 20))
        self.lineEdit_start.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_start.setObjectName("lineEdit_start")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(171, 120, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 60, 801, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(171, 230, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(171, 160, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color : rgb(255, 255, 255)")
        self.label_7.setObjectName("label_7")
        self.lineEdit_end = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_end.setGeometry(QtCore.QRect(331, 200, 181, 20))
        self.lineEdit_end.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_end.setObjectName("lineEdit_end")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(1, 40, 801, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.line.setFont(font)
        self.line.setStyleSheet("padding: 15px 25px;\n"
"  font-size: 24px;\n"
"  text-align: center;\n"
"  cursor: pointer;\n"
"  outline: none;\n"
"  color: #fff;\n"
"  background-color: rgb(0, 255, 238);\n"
"  border: none;\n"
"  border-radius: 15px;\n"
"  box-shadow: 0 9px #999;")
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btn_insert = QtWidgets.QPushButton(self.centralwidget)
        self.btn_insert.setGeometry(QtCore.QRect(430, 320, 91, 41))
        self.btn_insert.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(170, 255, 0);")
        self.btn_insert.setObjectName("btn_insert")
        self.lineEdit_serial = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_serial.setGeometry(QtCore.QRect(331, 240, 181, 20))
        self.lineEdit_serial.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_serial.setObjectName("lineEdit_serial")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(220, 400, 301, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_hasil = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(15)
        self.label_hasil.setFont(font)
        self.label_hasil.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_hasil.setText("")
        self.label_hasil.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hasil.setObjectName("label_hasil")
        self.horizontalLayout_2.addWidget(self.label_hasil)
        self.lineEdit_guarantee = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_guarantee.setGeometry(QtCore.QRect(330, 280, 181, 20))
        self.lineEdit_guarantee.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_guarantee.setText("")
        self.lineEdit_guarantee.setObjectName("lineEdit_guarantee")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(170, 270, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        insert_guarantee.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(insert_guarantee)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        insert_guarantee.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(insert_guarantee)
        self.statusbar.setObjectName("statusbar")
        insert_guarantee.setStatusBar(self.statusbar)

        self.btn_insert.clicked.connect(self.insert)

        self.retranslateUi(insert_guarantee)
        QtCore.QMetaObject.connectSlotsByName(insert_guarantee)

    def retranslateUi(self, insert_guarantee):
        _translate = QtCore.QCoreApplication.translate
        insert_guarantee.setWindowTitle(_translate("insert_guarantee", "MainWindow"))
        self.label_3.setText(_translate("insert_guarantee", "Insert"))
        self.label_2.setText(_translate("insert_guarantee", "Service Center Handphone & Laptop"))
        self.label.setText(_translate("insert_guarantee", "Hai, Admin"))
        self.label_5.setText(_translate("insert_guarantee", "End Date"))
        self.label_6.setText(_translate("insert_guarantee", "Guarantee ID"))
        self.label_4.setText(_translate("insert_guarantee", "INSERT A GUARANTEE"))
        self.label_8.setText(_translate("insert_guarantee", "Serial Number"))
        self.label_7.setText(_translate("insert_guarantee", "Start Date"))
        self.btn_insert.setText(_translate("insert_guarantee", "INSERT"))
        self.label_9.setText(_translate("insert_guarantee", "Guarantee Product ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    insert_guarantee = QtWidgets.QMainWindow()
    ui = Ui_insert_guarantee()
    ui.setupUi(insert_guarantee)
    insert_guarantee.show()
    sys.exit(app.exec_())
