# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_guarantee.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql

class Ui_update_guarantee(object):
    def update(self):
        db = pymysql.connect("localhost","root","","bingung")
        cur = db.cursor()
        a = self.lineEdit_kd.text()
        b = self.lineEdit_kd_2.text()
        c = self.comboBox.currentText()
        if c == "Guarantee ID":
            cur.execute("UPDATE guarantee SET guarantee_id ='"+b+"' WHERE guarantee_id='"+a+"' ")
        elif c == "Guarantee Start Date":
            cur.execute("UPDATE guarantee SET guarantee_start_date='"+b+"' WHERE guarantee_id='"+a+"' ")
        elif c == "Guarantee End Date":
            cur.execute("UPDATE guarantee SET guarantee_end_date ='" + b + "' WHERE guarantee_id='" + a + "' ")
        elif c =="Guarantee Serial":
            cur.execute("UPDATE guarantee SET guarantee_serial ='" + b + "' WHERE guarantee_id='" + a + "' ")
        elif c =="Guarantee Product ID":
            cur.execute("UPDATE guarantee SET guarantee_product_id ='" + b + "' WHERE guarantee_id='" + a + "' ")
        db.commit()
    def setupUi(self, update_guarantee):
        update_guarantee.setObjectName("update_guarantee")
        update_guarantee.resize(783, 600)
        update_guarantee.setStyleSheet("background-color: rgb(112, 112, 112);")
        self.centralwidget = QtWidgets.QWidget(update_guarantee)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_insert = QtWidgets.QPushButton(self.centralwidget)
        self.btn_insert.setGeometry(QtCore.QRect(440, 300, 101, 41))
        self.btn_insert.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(170, 255, 0);")
        self.btn_insert.setObjectName("btn_insert")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(320, 200, 180, 22))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_kd = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_kd.setGeometry(QtCore.QRect(370, 140, 181, 20))
        self.lineEdit_kd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_kd.setObjectName("lineEdit_kd")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 60, 801, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(250, 140, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 40, 781, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(781, 0))
        self.line.setMaximumSize(QtCore.QSize(781, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.line.setFont(font)
        self.line.setStyleSheet("  padding: 15px 25px;\n"
"  font-size: 15px;\n"
"  text-align: center;\n"
"  cursor: pointer;\n"
"  outline: none;\n"
"color: rgb(60, 1, 255);\n"
"  background-color: rgb(0, 255, 238);\n"
"  border: none;\n"
"  border-radius: 15px;\n"
"  box-shadow: 0 9px #999;\n"
"hover{color:red}")
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 780, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        spacerItem = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.label_menu = QtWidgets.QLabel(self.centralwidget)
        self.label_menu.setGeometry(QtCore.QRect(110, 230, 591, 21))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_menu.setFont(font)
        self.label_menu.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_menu.setText("")
        self.label_menu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_menu.setObjectName("label_menu")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(200, 170, 431, 21))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(240, 110, 321, 21))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.lineEdit_kd_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_kd_2.setGeometry(QtCore.QRect(250, 260, 311, 20))
        self.lineEdit_kd_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_kd_2.setObjectName("lineEdit_kd_2")
        update_guarantee.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(update_guarantee)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 21))
        self.menubar.setObjectName("menubar")
        update_guarantee.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(update_guarantee)
        self.statusbar.setObjectName("statusbar")
        update_guarantee.setStatusBar(self.statusbar)

        self.btn_insert.clicked.connect(self.update)

        self.retranslateUi(update_guarantee)
        QtCore.QMetaObject.connectSlotsByName(update_guarantee)

    def retranslateUi(self, update_guarantee):
        _translate = QtCore.QCoreApplication.translate
        update_guarantee.setWindowTitle(_translate("update_guarantee", "MainWindow"))
        self.btn_insert.setText(_translate("update_guarantee", "Update Guarantee"))
        self.comboBox.setItemText(0, _translate("update_guarantee", "Guarantee ID"))
        self.comboBox.setItemText(1, _translate("update_guarantee", "Guarantee Start Date"))
        self.comboBox.setItemText(2, _translate("update_guarantee", "Guarantee End Date"))
        self.comboBox.setItemText(3, _translate("update_guarantee", "Guarantee Serial"))
        self.comboBox.setItemText(4, _translate("update_guarantee", "Guarantee Product ID"))
        self.label_10.setText(_translate("update_guarantee", "UPDATE A GUARANTEE"))
        self.label_6.setText(_translate("update_guarantee", "Guarantee ID"))
        self.line.setWhatsThis(_translate("update_guarantee", "<html><head/><body><p>s</p></body></html>"))
        self.label_7.setText(_translate("update_guarantee", "UPDATE"))
        self.label_8.setText(_translate("update_guarantee", "Service Center"))
        self.label_9.setText(_translate("update_guarantee", "Hai, Admin"))
        self.label_12.setText(_translate("update_guarantee", "Pilih menu yang ingin anda update"))
        self.label_11.setText(_translate("update_guarantee", "Masukkan ID garansi yang ingin anda update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    update_guarantee = QtWidgets.QMainWindow()
    ui = Ui_update_guarantee()
    ui.setupUi(update_guarantee)
    update_guarantee.show()
    sys.exit(app.exec_())
