# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert_user.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
import hashlib

class Ui_insert_user(object):
    def insert(self):
        db = pymysql.connect("localhost","root","","bingung")
        cur = db.cursor()
        a = self.lineEdit_id.text()
        b = self.lineEdit_nama.text()
        c = self.lineEdit_alamat.text()
        d = self.lineEdit_telepon.text()
        e = self.lineEdit_email.text()
        if self.b_pria.isChecked() == True:
            f = "Pria"
        elif self.b_wanita.isChecked() == True:
            f = "Wanita"
        g = self.comboBox.currentText()
        h = self.lineEdit_user.text()
        i = hashlib.md5(self.lineEdit_password.text().encode('utf-8')).hexdigest()
        cur.execute("INSERT INTO user VALUES ('"+a+"','"+b+"','"+c+"','"+d+"','"+e+"','"+f+"','"+g+"','"+h+"','"+i+"') ")
        db.commit()

    def setupUi(self, insert_user):
        insert_user.setObjectName("insert_user")
        insert_user.resize(800, 600)
        insert_user.setStyleSheet("background-color: rgb(112, 112, 112);")
        self.centralwidget = QtWidgets.QWidget(insert_user)
        self.centralwidget.setObjectName("centralwidget")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(171, 160, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color : rgb(255, 255, 255)")
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(171, 190, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.lineEdit_telepon = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_telepon.setGeometry(QtCore.QRect(331, 240, 181, 20))
        self.lineEdit_telepon.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_telepon.setObjectName("lineEdit_telepon")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(1, 40, 801, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.line.setFont(font)
        self.line.setStyleSheet("padding: 15px 25px;\n"
"  font-size: 24px;\n"
"  text-align: center;\n"
"  cursor: pointer;\n"
"  outline: none;\n"
"  color: #fff;\n"
"  background-color: rgb(0, 255, 238);\n"
"  border: none;\n"
"  border-radius: 15px;\n"
"  box-shadow: 0 9px #999;")
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setGeometry(QtCore.QRect(331, 120, 181, 20))
        self.lineEdit_id.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(171, 120, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(171, 230, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.btn_insert = QtWidgets.QPushButton(self.centralwidget)
        self.btn_insert.setGeometry(QtCore.QRect(430, 500, 91, 41))
        self.btn_insert.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(170, 255, 0);")
        self.btn_insert.setObjectName("btn_insert")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(170, 270, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 60, 801, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 0, 801, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_email = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_email.setGeometry(QtCore.QRect(330, 280, 181, 20))
        self.lineEdit_email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_email.setText("")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.lineEdit_nama = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nama.setGeometry(QtCore.QRect(331, 160, 181, 20))
        self.lineEdit_nama.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_nama.setObjectName("lineEdit_nama")
        self.lineEdit_alamat = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_alamat.setGeometry(QtCore.QRect(331, 200, 181, 20))
        self.lineEdit_alamat.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_alamat.setObjectName("lineEdit_alamat")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(170, 390, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(169, 430, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.lineEdit_user = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_user.setGeometry(QtCore.QRect(330, 400, 181, 20))
        self.lineEdit_user.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(170, 320, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color : rgb(255, 255, 255)")
        self.label_12.setObjectName("label_12")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setGeometry(QtCore.QRect(329, 440, 181, 20))
        self.lineEdit_password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_password.setText("")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(170, 350, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.b_pria = QtWidgets.QRadioButton(self.centralwidget)
        self.b_pria.setGeometry(QtCore.QRect(330, 320, 82, 17))
        self.b_pria.setStyleSheet("color: rgb(255, 255, 255);")
        self.b_pria.setObjectName("b_pria")
        self.b_wanita = QtWidgets.QRadioButton(self.centralwidget)
        self.b_wanita.setGeometry(QtCore.QRect(430, 320, 82, 17))
        self.b_wanita.setStyleSheet("color: rgb(255, 255, 255);")
        self.b_wanita.setObjectName("b_wanita")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(330, 360, 181, 22))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        insert_user.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(insert_user)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        insert_user.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(insert_user)
        self.statusbar.setObjectName("statusbar")
        insert_user.setStatusBar(self.statusbar)

        self.btn_insert.clicked.connect(self.insert)

        self.retranslateUi(insert_user)
        QtCore.QMetaObject.connectSlotsByName(insert_user)

    def retranslateUi(self, insert_user):
        _translate = QtCore.QCoreApplication.translate
        insert_user.setWindowTitle(_translate("insert_user", "MainWindow"))
        self.label_7.setText(_translate("insert_user", "Nama"))
        self.label_5.setText(_translate("insert_user", "Alamat"))
        self.label_6.setText(_translate("insert_user", "User ID"))
        self.label_8.setText(_translate("insert_user", "Telepon"))
        self.btn_insert.setText(_translate("insert_user", "INSERT"))
        self.label_9.setText(_translate("insert_user", "Email"))
        self.label_4.setText(_translate("insert_user", "INSERT A USER"))
        self.label_3.setText(_translate("insert_user", "Insert"))
        self.label_2.setText(_translate("insert_user", "Service Center Handphone & Laptop"))
        self.label.setText(_translate("insert_user", "Hai, Admin"))
        self.label_10.setText(_translate("insert_user", "User Name"))
        self.label_11.setText(_translate("insert_user", "Password"))
        self.label_12.setText(_translate("insert_user", "Gender"))
        self.label_13.setText(_translate("insert_user", "Position"))
        self.b_pria.setText(_translate("insert_user", "Pria"))
        self.b_wanita.setText(_translate("insert_user", "Wanita"))
        self.comboBox.setItemText(0, _translate("insert_user", "Manager"))
        self.comboBox.setItemText(1, _translate("insert_user", "Operator"))
        self.comboBox.setItemText(2, _translate("insert_user", "Engineer"))
        self.comboBox.setItemText(3, _translate("insert_user", "Administrator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    insert_user = QtWidgets.QMainWindow()
    ui = Ui_insert_user()
    ui.setupUi(insert_user)
    insert_user.show()
    sys.exit(app.exec_())
