# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Insert_component.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql

class Ui_Insert_component(object):
    def insert(self):
        db = pymysql.connect("localhost", "root", "", "bingung")
        cur = db.cursor()
        a = self.lineEdit_kd.text()
        b = self.lineEdit_nama.text()
        c = self.lineEdit_kategori.text()
        d = self.lineEdit_status.text()
        cur.execute("INSERT INTO component VALUES('" + a + "', '" + b + "', '" + c + "', '" + d + "'); ")
        db.commit()
    def setupUi(self, Insert_component):
        Insert_component.setObjectName("Insert_component")
        Insert_component.resize(800, 600)
        Insert_component.setStyleSheet("background-color: rgb(112, 112, 112);")
        self.centralwidget = QtWidgets.QWidget(Insert_component)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_insert = QtWidgets.QPushButton(self.centralwidget)
        self.btn_insert.setGeometry(QtCore.QRect(430, 280, 91, 41))
        self.btn_insert.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(170, 255, 0);")
        self.btn_insert.setObjectName("btn_insert")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(210, 120, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.lineEdit_kd = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_kd.setGeometry(QtCore.QRect(330, 120, 181, 20))
        self.lineEdit_kd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_kd.setObjectName("lineEdit_kd")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(210, 190, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(210, 160, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color : rgb(255, 255, 255)")
        self.label_7.setObjectName("label_7")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(220, 360, 301, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_hasil = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(15)
        self.label_hasil.setFont(font)
        self.label_hasil.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_hasil.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hasil.setObjectName("label_hasil")
        self.horizontalLayout_2.addWidget(self.label_hasil)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 60, 801, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit_kategori = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_kategori.setGeometry(QtCore.QRect(330, 200, 181, 20))
        self.lineEdit_kategori.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_kategori.setObjectName("lineEdit_kategori")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 40, 801, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.line.setFont(font)
        self.line.setStyleSheet("padding: 15px 25px;\n"
"  font-size: 24px;\n"
"  text-align: center;\n"
"  cursor: pointer;\n"
"  outline: none;\n"
"  color: #fff;\n"
"  background-color: rgb(0, 255, 238);\n"
"  border: none;\n"
"  border-radius: 15px;\n"
"  box-shadow: 0 9px #999;")
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(210, 230, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Iskoola Pota")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.lineEdit_status = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_status.setGeometry(QtCore.QRect(330, 240, 181, 20))
        self.lineEdit_status.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_status.setObjectName("lineEdit_status")
        self.lineEdit_nama = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nama.setGeometry(QtCore.QRect(330, 160, 181, 20))
        self.lineEdit_nama.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_nama.setObjectName("lineEdit_nama")
        Insert_component.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Insert_component)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Insert_component.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Insert_component)
        self.statusbar.setObjectName("statusbar")
        Insert_component.setStatusBar(self.statusbar)

        self.btn_insert.clicked.connect(self.insert)

        self.retranslateUi(Insert_component)
        QtCore.QMetaObject.connectSlotsByName(Insert_component)

    def retranslateUi(self, Insert_component):
        _translate = QtCore.QCoreApplication.translate
        Insert_component.setWindowTitle(_translate("Insert_component", "MainWindow"))
        self.btn_insert.setText(_translate("Insert_component", "Insert Product"))
        self.label_6.setText(_translate("Insert_component", "Kode Komponen"))
        self.label_5.setText(_translate("Insert_component", "Harga Komponen"))
        self.label_7.setText(_translate("Insert_component", "Nama Komponen"))
        self.label_hasil.setText(_translate("Insert_component", "Masukkan kode komponen"))
        self.label_4.setText(_translate("Insert_component", "INSERT A COMPONENT"))
        self.label_3.setText(_translate("Insert_component", "Insert"))
        self.label_2.setText(_translate("Insert_component", "Service Center Handphone & Laptop"))
        self.label.setText(_translate("Insert_component", "Hai, Admin"))
        self.label_8.setText(_translate("Insert_component", "Qty"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Insert_component = QtWidgets.QMainWindow()
    ui = Ui_Insert_component()
    ui.setupUi(Insert_component)
    Insert_component.show()
    sys.exit(app.exec_())
